development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pollingdb_development
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pollingdb_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: pollingdb_production
  pool: 5
  username: rails_user
  password: mint06 